landing/urls.py
from django.conf.urls import url
from . import views

app_name = 'landing'

urlpatterns = [
    #/
    url(r'^$', views.index, name='index'),

    #/413/favorite
    # url(r'^(?P<game_id>[0-9]+)/favorite/$', views.favorite, name='detail' ),

    url(r'^(?P<game_id>[0-9]+)/vote/$', views.vote, name='vote'),

    #/413
    url(r'^(?P<game_id>[0-9]+)$', views.detail, name='detail' ),

    url(r'^(?P<game_id>[0-9]+)/result/$', views.result, name='result'),

    url(r'^play_turd/$', views.flappy_turd, name='flappy'),

    url(r'^spacegame/$', views.spacegame, name='spacegame'),

    url(r'^fannydritz/$', views.fannydritz, name='fannydritz')


]

pythonArcade/landingPage/urls.py
from django.conf.urls import url
from . import views
# Create your views here.
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

pythonArcade/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('landing.urls')),
]

landing/models.py
from __future__ import unicode_literals

from django.db import models

class Game(models.Model):
    name = models.CharField(max_length=200)
    descriptions = models.CharField(max_length=500)
    link = models.CharField(max_length=200)
    pic = models.CharField(max_length=20)

    #
    def __str__(self):
        return self.name

class Poll(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

landing/views.py
from django.shortcuts import render, get_object_or_404
from .models import Game, Poll
from django.http import HttpResponseRedirect
from django.urls import reverse

def index(request):
    all_games = Game.objects.all()
    return render(request, 'landing/index.html', {'all_games': all_games})

def flappy_turd(request):
    return render(request, 'landing/flappy_turd.html')

def spacegame(request):
    return render(request, 'landing/spacegame.html')

def fannydritz(request):
    return render(request, 'landing/fannydritz.html')

def detail(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    return render(request, 'landing/detail.html', {'game': game})

def result(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    return render(request, 'landing/result.html', {'game': game})


def vote(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    try:
        selected_choice = game.poll_set.get(pk=request.POST['choice'])
    except (KeyError, choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'game': game,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.

        return HttpResponseRedirect(reverse('landing:result', args=(game.id,)))

landing/templates/landing/detail.html
<!DOCTYPE html> {%load staticfiles%}

<html>


<head>
    <meta charset="utf-8">
    <title>Python Arcade</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css" rel="stylesheet" integrity="sha384-Xqcy5ttufkC3rBa8EdiAyA1VgOGrmel2Y+wxm4K3kI3fcjTWlDWrlnxyD6hOi3PF" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'landing/style.css' %}">

</head>

<body>

    <nav id='bar' class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Python Arcade</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            </div>
        </div>
    </nav>
    <div class='box'>
        <h1 class='game_name'>{{game.name}}</h1>
        <h3 id='descript'>{{game.descriptions}}</h3>
        <div class={{game.pic}}></div>
        <a id='button' href="{{game.link}}" class="btn btn-primary btn-lg">Play Game</a> {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>{% endif %}
    </div>

    <form class="form-horizontal" action="{% url 'landing:vote' game.id %}" method="post">
        <fieldset>
          <div class="form-group">
            <div class="col-lg-10">
            <legend>What do you think about this game?</legend>
            {% csrf_token %} {% for poll in game.poll_set.all %}
                    <div class='vote'>
                        <input class='vote' type='radio' name='choice' id='choice{{ forloop.counter }}' value="{{ poll.id }}">
                        <label for='choice {{ forloop.counter }}'>{{ poll.choice_text}}</lable>
                    </div>
      {% endfor %}
    </div>
  </div>
       <button id='vote_button' type="submit" class="btn btn-default">vote</button>
  </fieldset>
    </form>




</body>

</html>

landing/templates/landing/fannydritz.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Fanny Dritz VS The Homeless</title>
    <script src= {% static "landing/js/flappy/phaser.js" %}></script>
    <script src= {% static "landing/js/fannydritz/boot.js" %}></script>
    <script src= {% static "landing/js/fannydritz/Preloader.js" %}></script>
    <script src= {% static "landing/js/fannydritz/Level.js" %}></script>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Irish+Grover" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>

  </head>
  <body>
    <style>
    body {
      background-color: teal;
    }
    canvas {
      border: 5px solid black;
      margin-left: 41%;
      margin-top: 8%;
    }
    </style>

    <div class="container" style="margin-left:5%">

      <div style="position: fixed; font-family:'Irish Grover', cursive; color:#ffffff; margin-top:5%" class="col-md-4">
        <h1>Fanny Dritz VS. The Homeless</h1>
        <h2>Directions:</h2>
        <h3>Press A,S, & W to make Fanny move! Press SPACEBAR to launch a bird at foes!</h3>
        <h3>Avoid water, pits, and homeless combatants, as you make your through Commons Park to G-School!</h3>
      </div>

      <div style="margin-top:46%; margin-left:10%; position:fixed">
        <img src="http://piskel-imgstore-b.appspot.com/img/398f364c-a216-11e6-91f5-3792a41521d5.gif">
      </div>

    </div>





    <script type="text/javascript">
        window.onload = function() {
            var game = new Phaser.Game(500, 400, Phaser.AUTO, '');
            game.state.add('Boot', Game.Boot);
            game.state.add('Preloader', Game.Preloader);
            game.state.add('Level', Game.Level);
            game.state.add('GameOver', Game.GameOver);
            game.state.start('Boot');
          }
    </script>
    <script type="text/javascript" src= "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

landing/templates/landing/flappy_turd.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <title>Flappy Turd</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Irish+Grover" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
    <script type="text/javascript" src= {% static "landing/js/flappy/phaser.js" %}></script>

</head>

<body>

<style>

  body {
    background-color: #8b4513;
  }

  canvas {
    border: 5px solid black;
    margin-left: 45%;
    margin-top: 3%;
  }
</style>

<div class="container" style="margin-left:15%">

  <div style="position: fixed; font-family:'Irish Grover', cursive; color:#bc9055" class="col-md-3">
    <h1>Flappy Turd</h1>
    <h2>Directions:</h2>
    <h3>Press the SPACEBAR to elevate Flappy Turd.</h3>
    <h3>Avoid obstacles and earn points!</h3>

    <div style="margin-left: -50px">
      <img src="http://3.bp.blogspot.com/-vBPM9D-Q6QE/VQMqx2noDKI/AAAAAAAAIlY/-JRuvT-ILnM/s1600/a.png">
    </div>

  </div>


  <!-- <div>
    <h2 style="position: fixed; font-family:'Irish Grover', cursive"> Directions</h2>
  </div> -->

</div>





<script type="text/javascript" src= "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src= {% static "landing/js/flappy/main.js" %}></script>
</body>

</html>

landing/templates/landing/index.html
<!DOCTYPE html> {%load staticfiles%}
<html>

<head>
    <meta charset="utf-8">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css" rel="stylesheet" integrity="sha384-Xqcy5ttufkC3rBa8EdiAyA1VgOGrmel2Y+wxm4K3kI3fcjTWlDWrlnxyD6hOi3PF" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'landing/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title>Python Arcade</title>
</head>

<body>

    <nav id='bar' class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Python Arcade</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            </div>
        </div>
    </nav>

    <div class='main'>

        {% if all_games %}

            {% for game in all_games %}
            <div id='box' class="well">
            <a href="{% url 'landing:detail' game.id %}">
                <h1 class='game_name'>{{ game.name }}</h1>
                <div class={{game.pic}}>
                </div>
            </a>
            <h4 id='descript'>{{ game.descriptions }} </h4>
        </div>

        {% endfor %} {% else %}
        <h3> No games avliable </h3> {% endif %}
    </div>
</body>

</html>

landing/templates/landing/result.html
<!DOCTYPE html> {%load staticfiles%}


<html>


<head>
    <meta charset="utf-8">
    <title>Python Arcade</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css" rel="stylesheet" integrity="sha384-Xqcy5ttufkC3rBa8EdiAyA1VgOGrmel2Y+wxm4K3kI3fcjTWlDWrlnxyD6hOi3PF" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'landing/style.css' %}">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc=" crossorigin="anonymous"></script>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.bundle.js'></script>

</head>

<body>

    <nav id='bar' class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Python Arcade</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            </div>
        </div>
    </nav>
    <div class='box'>
        <h1 class='game_name'>{{game.name}}</h1>
        <h3 id='descript'>{{game.descriptions}}</h3>
        <div class={{game.pic}}></div>
        <a id='button' href="{{game.link}}" class="btn btn-primary btn-lg">Play Game</a> {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>{% endif %}
    </div>


<div class=result_vote>
<ul>
  {% for poll in game.poll_set.all %}
  <li>{{ poll.choice_text }}:  {{ poll.votes }} vote{{ poll.votes|pluralize }} </li>
  {% endfor %}
</ul>
</div>
  </body>
</html>

landing/templates/landing/spacegame.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script type="text/javascript" src= {% static "landing/js/flappy/phaser.js" %}></script>
    <script type="text/javascript" src= {% static "landing/js/spacegame/js/game.js" %}></script>
  </head>
  <body>
  <style>

    body {
      background-color: #848FA5;
    }

    canvas {
      border: 5px solid black;
      margin-left: 35%;
      margin-top: 3%;
    }
  </style>

  <div class="container" style="margin-left:7%">

    <div style="position: fixed; font-family:'Irish Grover', cursive; color:black" class="col-md-3">
      <h1>Space Shooter</h1>
      <h2>Directions:</h2>
      <h3>Press the SPACEBAR to fly the ship.</h3>
      <h3>Hit space bar to fire at the Aliens!</h3>

      <div style="margin-left: -10px">
        <img src="https://cdn.shopify.com/s/files/1/1061/1924/files/Alien_Emoji.png?8395986304114536760" style='height: 200px;'>
      </div>

    </div>

  </body>
</html>